windows:
- active: true
  geometry: !!binary |
    AdnQywADAAAAAAAAAAAAAAAABusAAASFAAAAAAAAAAAAAANwAAAEhQAAAAACAAAAB1MAAAAAAAAA
    AAAABusAAASF
  tabs:
  - active: true
    history:
    - last_visited: '2025-08-14T20:10:11'
      pinned: false
      title: Форк своего репозитория на GitHub - DeepSeek
      url: https://chat.deepseek.com/a/chat/s/46eaac11-b185-4c59-b6f6-fe25cbf4fdc3
    - active: true
      last_visited: '2025-08-14T20:10:14'
      pinned: false
      scroll-pos:
        x: 0
        y: 0
      title: DeepSeek - Into the Unknown
      url: https://chat.deepseek.com/
      zoom: 1.0
