windows:
- active: true
  geometry: !!binary |
    AdnQywADAAAAAAAAAAAAAAAAA3AAAASFAAAAAAAAAAAAAANwAAAEhQAAAAACAAAAB1MAAAAAAAAA
    AAAAA3AAAASF
  tabs:
  - active: true
    history:
    - active: true
      last_visited: '2025-08-14T17:54:25'
      pinned: false
      scroll-pos:
        x: 0
        y: 0
      title: Форк своего репозитория на GitHub - DeepSeek
      url: https://chat.deepseek.com/a/chat/s/46eaac11-b185-4c59-b6f6-fe25cbf4fdc3
      zoom: 1.0
