windows:
- active: true
  geometry: !!binary |
    AdnQywADAAAAAAAAAAAAAAAABusAAASFAAAAAAAAAAAAAAbrAAAEhQAAAAACAAAAB1MAAAAAAAAA
    AAAABusAAASF
  tabs:
  - active: true
    history:
    - last_visited: '2025-08-14T17:46:47'
      pinned: false
      title: DuckDuckGo - Protection. Privacy. Peace of mind.
      url: https://start.duckduckgo.com/
    - last_visited: '2025-08-14T17:46:57'
      pinned: false
      title: gitub at DuckDuckGo
      url: https://duckduckgo.com/?t=h_&hps=1&start=1&q=gitub&ia=web
    - last_visited: '2025-08-14T17:46:59'
      pinned: false
      title: GitHub 路 Build and ship software on a single, collaborative platform
        路 GitHub
      url: https://github.com/
    - last_visited: '2025-08-14T17:47:01'
      pinned: false
      title: Sign in to GitHub 路 GitHub
      url: https://github.com/login
    - last_visited: '2025-08-14T17:47:26'
      pinned: false
      title: Two-factor authentication 路 GitHub
      url: https://github.com/sessions/two-factor/mobile?auto=true
    - last_visited: '2025-08-14T17:47:40'
      pinned: false
      title: GitHub
      url: https://github.com/
    - last_visited: '2025-08-14T17:47:51'
      pinned: false
      title: Your Repositories
      url: https://github.com/NoSignificantWorries?tab=repositories
    - active: true
      last_visited: '2025-08-14T17:48:08'
      pinned: false
      scroll-pos:
        x: 0
        y: 0
      title: NoSignificantWorries (Dmitry)
      url: https://github.com/NoSignificantWorries
      zoom: 1.0
